server:
  port: 8001



spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.220.164.57:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: spring-cloud
    password: rchen@springcloud