server:
  port: 8802



spring:
  application:
    name: cloud-stream-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings: # 服务的整合处理
        myChannel-in-0: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要是用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置为 "text/plain"
          group: cloud-group-01

eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
       defaultZone: http://localhost:7001/eureka/
      # 集群
      # defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: consumer-8802.com # 在信息列表时显示的主机名称
    # 可显示ip
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 设置现在超过了5秒的间隔（默认是90秒）