server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能呢，利用微服务名称进行路由
      routes:
        - id: payment_routh   # 路由ID，没有固定规则但要求唯一，建议配合服务名称
          uri: lb://CLOUD-PROVIDER-PAYMENT   # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**   # 断言，路径相匹配的进行路由
            - After=2022-10-21T09:50:40.619696+08:00[Asia/Shanghai] # 某个时间之后可以访问
#        - id: payment_routh   # 路由ID，没有固定规则但要求唯一，建议配合服务名称
#          uri: http://localhost:8001   # 匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/hystrix/**   # 断言，路径相匹配的进行路由
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/hystrix/timeout/**

eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: gateway9527
    # 可显示ip
    prefer-ip-address: true